apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rng
  name: rng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
        enabled: "no"
    spec:
      containers:
      - image: dockercoins/rng:v0.1
        name: rng
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: rng
  name: rng
spec:
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
        enabled: "yes"
    spec:
      terminationGracePeriodSeconds: 3
      containers:
      - image: dockercoins/rng:v0.1
        name: rng
        ports:
        - containerPort: 80
        # https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-liveness-http-request
        readinessProbe:
          httpGet:
            path: /20
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 10
          periodSeconds: 3
          failureThreshold: 3
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              awk '{ if ($1 < 60) exit 0; else exit 1 }' /proc/uptime
          initialDelaySeconds: 50
          periodSeconds: 1
          failureThreshold: 1


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: rng
  name: rng
spec:
  ports:
  - port: 80
  selector:
    app: rng
    enabled: "yes"
